name: Deploy to servers

on:
  

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
          role-to-assume: ${{ secrets.ROLE_ARN }} 
          role-duration-seconds: 900  
